const GET_ALL_SUBJECT_LIST = 'GET_ALL_SUBJECT_LIST';
const GET_INTERVIEW_DATA_BY_TOPIC_NAME = 'GET_INTERVIEW_DATA_BY_TOPIC_NAME';

export {
    GET_ALL_SUBJECT_LIST,
    GET_INTERVIEW_DATA_BY_TOPIC_NAME,
}